/* eslint-disable no-console */
// Builds the withdraw circuit end to end:
//   circom compile -> ptau download -> Groth16 setup -> Solidity verifier
//   -> proving assets copied to apps/web/public/zk/
// Run from packages/contracts: node scripts/build-circuit.js

const { execFileSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const BUILD = path.join(ROOT, "circuits", "build");
const PTAU_URL =
  "https://storage.googleapis.com/zkevm/ptau/powersOfTau28_hez_final_14.ptau";
const PTAU = path.join(BUILD, "powersOfTau28_hez_final_14.ptau");
const R1CS = path.join(BUILD, "withdraw.r1cs");
const WASM = path.join(BUILD, "withdraw_js", "withdraw.wasm");
const ZKEY_0 = path.join(BUILD, "withdraw_0000.zkey");
const ZKEY_FINAL = path.join(BUILD, "withdraw_final.zkey");
const VKEY = path.join(BUILD, "verification_key.json");
const VERIFIER_SOL = path.join(ROOT, "contracts", "Groth16Verifier.sol");
const WEB_ZK_DIR = path.join(ROOT, "..", "..", "apps", "web", "public", "zk");

async function downloadPtau() {
  if (fs.existsSync(PTAU)) {
    console.log("ptau already present, skipping download");
    return;
  }
  console.log("downloading ptau (~19 MB)…");
  const res = await fetch(PTAU_URL);
  if (!res.ok) throw new Error(`ptau download failed: ${res.status}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  fs.writeFileSync(PTAU, buffer);
  console.log(`ptau saved (${(buffer.length / 1e6).toFixed(1)} MB)`);
}

function resolveCircomInvocation() {
  // Windows dev: optional native binary in .tools/
  const localExe = path.join(ROOT, "..", "..", ".tools", "circom.exe");
  if (fs.existsSync(localExe)) {
    return { command: localExe, prefixArgs: [] };
  }

  // npm dependency — works in Codespaces / Linux without a global circom install
  const circom2Cli = require.resolve("circom2/cli.js");
  return { command: process.execPath, prefixArgs: [circom2Cli] };
}

function resolveCircomlibIncludePath() {
  const pkgDir = path.dirname(require.resolve("circomlib/package.json"));
  const poseidon = path.join(pkgDir, "circuits", "poseidon.circom");
  if (fs.existsSync(poseidon)) return pkgDir;

  const roots = [path.join(ROOT, "..", ".."), ROOT];
  for (const root of roots) {
    const candidate = path.join(root, "node_modules", "circomlib");
    const candidatePoseidon = path.join(candidate, "circuits", "poseidon.circom");
    if (fs.existsSync(candidatePoseidon)) return candidate;
  }

  throw new Error(
    "circomlib circuits not found. From the repo root run: npm install",
  );
}

function compileCircuit() {
  console.log("compiling withdraw.circom…");
  const circomlibRoot = resolveCircomlibIncludePath();
  const { command, prefixArgs } = resolveCircomInvocation();
  execFileSync(
    command,
    [
      ...prefixArgs,
      path.join(ROOT, "circuits", "withdraw.circom"),
      "--r1cs",
      "--wasm",
      "-o",
      BUILD,
      "-l",
      circomlibRoot,
    ],
    { stdio: "inherit", cwd: ROOT },
  );
}

async function setupZkey(snarkjs) {
  console.log("groth16 setup…");
  await snarkjs.zKey.newZKey(R1CS, PTAU, ZKEY_0);

  console.log("zkey contribution…");
  const entropy = require("node:crypto").randomBytes(32).toString("hex");
  await snarkjs.zKey.contribute(ZKEY_0, ZKEY_FINAL, "z-tor phase1 dev", entropy);

  const vkey = await snarkjs.zKey.exportVerificationKey(ZKEY_FINAL);
  fs.writeFileSync(VKEY, JSON.stringify(vkey, null, 2));
}

async function exportVerifier(snarkjs) {
  console.log("exporting Solidity verifier…");
  // snarkjs blocks subpath resolution via "exports" — locate it from main.
  const snarkjsRoot = path.join(path.dirname(require.resolve("snarkjs")), "..");
  const templatePath = path.join(snarkjsRoot, "templates", "verifier_groth16.sol.ejs");
  const template = fs.readFileSync(templatePath, "utf8");
  let solidity = await snarkjs.zKey.exportSolidityVerifier(ZKEY_FINAL, {
    groth16: template,
  });
  solidity = `// solhint-disable\n// Generated by snarkjs from circuits/withdraw.circom — do not edit.\n${solidity}`;
  fs.writeFileSync(VERIFIER_SOL, solidity);
}

function sha256File(filePath) {
  const crypto = require("node:crypto");
  return crypto.createHash("sha256").update(fs.readFileSync(filePath)).digest("hex");
}

function copyWebAssets() {
  fs.mkdirSync(WEB_ZK_DIR, { recursive: true });
  const wasmOut = path.join(WEB_ZK_DIR, "withdraw.wasm");
  const zkeyOut = path.join(WEB_ZK_DIR, "withdraw_final.zkey");
  const vkeyOut = path.join(WEB_ZK_DIR, "verification_key.json");
  fs.copyFileSync(WASM, wasmOut);
  fs.copyFileSync(ZKEY_FINAL, zkeyOut);
  fs.copyFileSync(VKEY, vkeyOut);

  const manifest = {
    version: 1,
    circuit: "withdraw",
    publicInputs: ["root", "nullifierHash", "recipient", "relayer", "fee"],
    files: {
      "withdraw.wasm": sha256File(wasmOut),
      "withdraw_final.zkey": sha256File(zkeyOut),
      "verification_key.json": sha256File(vkeyOut),
    },
  };
  fs.writeFileSync(
    path.join(WEB_ZK_DIR, "manifest.json"),
    JSON.stringify(manifest, null, 2),
  );
  console.log(`proving assets copied to ${WEB_ZK_DIR}`);
}

async function main() {
  fs.mkdirSync(BUILD, { recursive: true });
  compileCircuit();
  await downloadPtau();
  const snarkjs = require("snarkjs");
  await setupZkey(snarkjs);
  await exportVerifier(snarkjs);
  copyWebAssets();
  console.log("circuit build complete");
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
